---
# tasks file for win_ad_install

- name: ping windows machine
  win_ping:

- name: Install Active Directory Service
  win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: yes
    include_sub_feaures: yes
  register: win_feature

- name: Set Up Active Directory And DNS Service
  win_domain:
    dns_domain_name: "ad1.1e77.example.opentlc.com" 
    safe_mode_password: "{{ansible_password}}"
  ignore_errors: yes

- name: Reboot windows machine
  win_reboot:
  when: win_feature.reboot_required

- name: List out domain list
  win_command: nltest /dclist:"{{ ad_domain_name }}"
  register: output
  ignore_errors: yes

- debug:
    var: output['stdout_lines'] 


 


